# Generated by Django 4.2.7 on 2024-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('idantecedentes', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'antecedentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cabeza',
            fields=[
                ('id_cabeza', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor_total', models.CharField(blank=True, max_length=45, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cabeza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('imagen', models.ImageField(null=True, upload_to='categoria')),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id_cuerpo', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_unitario', models.CharField(max_length=45)),
                ('valor_total', models.CharField(max_length=45)),
                ('descuento', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cuerpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesarrolloSesion',
            fields=[
                ('id_desarrollo_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=220)),
            ],
            options={
                'db_table': 'desarrollo_sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('tipo_diagnostico_id_tipo_diagnostico', models.IntegerField()),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id_especialidades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id_evolucion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenMental',
            fields=[
                ('id_examen_mental', models.IntegerField(primary_key=True, serialize=False)),
                ('examen_mental', models.CharField(db_collation='utf8_spanish_ci', max_length=300)),
            ],
            options={
                'db_table': 'examen_mental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaPsico',
            fields=[
                ('id_experiencia_psico', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'experiencia_psico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoresProtectores',
            fields=[
                ('id_factores_protectores', models.IntegerField(primary_key=True, serialize=False)),
                ('factores_protectores', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'factores_protectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactoresRiesgo',
            fields=[
                ('id_factores_riesgo', models.IntegerField(primary_key=True, serialize=False)),
                ('factores_riesgo', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'factores_riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia_clinica', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'historia_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaVida',
            fields=[
                ('id_historia_vida', models.IntegerField(primary_key=True, serialize=False)),
                ('historia_vida', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'historia_vida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoConsulta',
            fields=[
                ('id_motivo_consulta', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(db_collation='utf8_spanish_ci', db_column='Motivo_Consulta', max_length=120)),
            ],
            options={
                'db_table': 'motivo_consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paquetes',
            fields=[
                ('id_paquetes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'paquetes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('nombre2', models.CharField(blank=True, db_collation='utf8_spanish_ci', max_length=70, null=True)),
                ('apellido1', models.CharField(db_collation='utf8_spanish_ci', max_length=30)),
                ('apellido2', models.CharField(blank=True, db_collation='utf8_spanish_ci', max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=45)),
                ('nombre_responsable', models.CharField(blank=True, max_length=45, null=True)),
                ('eps', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(max_length=45)),
                ('cedula', models.CharField(blank=True, max_length=45, null=True)),
                ('imagen', models.CharField(blank=True, max_length=45, null=True)),
                ('genero', models.CharField(blank=True, max_length=45, null=True)),
                ('estadocivil', models.CharField(blank=True, db_column='estadoCivil', max_length=45, null=True)),
                ('tipodocumento', models.CharField(blank=True, db_column='tipoDocumento', max_length=45, null=True)),
                ('numerodocumento', models.IntegerField(blank=True, db_column='numeroDocumento', null=True)),
                ('lugar_nacimiento', models.CharField(db_column='lugar nacimiento', max_length=45)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_profesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'profesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionPersona',
            fields=[
                ('id_profesion_persona', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesion_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecursosEducativos',
            fields=[
                ('id_recursos_educativos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'recursos_educativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionFamiliar',
            fields=[
                ('id_relacion_familiar', models.IntegerField(primary_key=True, serialize=False)),
                ('relacion_familiar', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'relacion_familiar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id_remision', models.IntegerField(primary_key=True, serialize=False)),
                ('profesional', models.CharField(db_collation='utf8_spanish_ci', max_length=220)),
                ('descripcion', models.IntegerField()),
            ],
            options={
                'db_table': 'remision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('pregunta1', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('pregunta2', models.CharField(max_length=60)),
                ('respuesta1', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='utf8_spanish_ci', max_length=70)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=120)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_collation='utf8_spanish_ci', max_length=220)),
                ('numero_sesiones', models.IntegerField()),
            ],
            options={
                'db_table': 'tratamiento',
                'managed': False,
            },
        ),
    ]
